### ISSUE TITLE
NiftyNet Singularity Container outdated?

### ISSUE THREAD

**Issue by nzxwang** [khanlab/niftynet_hackathon#1]
I tried to follow the instructions under the heading "Run NiftyNet with singularity container(note: Linux with GPU only)" of readme.md and I get a `The NiftyNetExamples server is not running` error that seems to be closed on July 11, 2018 (ref: [https://github.com/NifTK/NiftyNet/issues/55](https://github.com/NifTK/NiftyNet/issues/55)). 

```
(develop) [nzxwang@gra-login2 2019-05-21_NiftyNet]$ singularity exec --nv deeplearning_gpu.simg net_download dense_vnet_abdominal_ct_model_zoo
Accessing: https://github.com/NifTK/NiftyNetModelZoo
The NiftyNetExamples server is not running
```

**Comment by akhanf** [comment]
@yinglilu are you able to reproduce this error?

**Comment by yinglilu** [comment]
Hi nzxwang,

Tried on my machine, nothing wrong.  Seems like a server problem. Can you try it again?

Accessing: https://github.com/NifTK/NiftyNetModelZoo
Downloading from https://github.com/NifTK/NiftyNetModelZoo/raw/5-reorganising-with-lfs/dense_vnet_abdominal_ct/code.tar.gz
dense_vnet_abdominal_ct_model_zoo -- code: OK.
Downloaded data to /home/ROBARTS/ylu/niftynet/extensions/dense_vnet_abdominal_ct
Downloading from https://github.com/NifTK/NiftyNetModelZoo/raw/5-reorganising-with-lfs/dense_vnet_abdominal_ct/data.tar.gz
Downloading (total: 3.61 M):  |==========| 100.0%

dense_vnet_abdominal_ct_model_zoo -- data: OK.
Downloaded data to /home/ROBARTS/ylu/niftynet/data/dense_vnet_abdominal_ct
Downloading from https://github.com/NifTK/NiftyNetModelZoo/raw/5-reorganising-with-lfs/dense_vnet_abdominal_ct/weights.tar.gz
Downloading (total: 9.68 M):  |==========| 100.0%

dense_vnet_abdominal_ct_model_zoo -- weights: OK.
Downloaded data to /home/ROBARTS/ylu/niftynet/models/dense_vnet_abdominal_ct

**Comment by akhanf** [comment]
I just tried it myself on the graham login node, and got the same error as @nzxwang

**Comment by nzxwang** [comment]
I have been and still am trying to install NiftyNet into a python virtual environment on the login node. 
UPDATE: In a new python/3.6.3 virtual environment, my installation of NiftyNet gives a different error

```
(NiftyNet_python3.6.3) [nzxwang@gra-login1 2019-05-21_NiftyNet]$ net_download dense_vnet_abdominal_ct_model_zoo
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
Traceback (most recent call last):
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/bin/net_download", line 7, in <module>
    from niftynet.utilities.download import main
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/lib/python3.6/site-packages/niftynet/__init__.py", line 15, in <module>
    import tensorflow as tf
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/lib/python3.6/site-packages/tensorflow/python/keras/activations.py", line 24, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/lib/python3.6/site-packages/tensorflow/python/keras/utils/__init__.py", line 32, in <module>
    from tensorflow.python.keras.utils.io_utils import HDF5Matrix
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/lib/python3.6/site-packages/tensorflow/python/keras/utils/io_utils.py", line 29, in <module>
    import h5py
  File "/home/nzxwang/venv/NiftyNet_python3.6.3/lib/python3.6/site-packages/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5t.pxd", line 14, in init h5py._conv
  File "h5py/h5t.pyx", line 1, in init h5py.h5t
SystemError: execution of module h5py.utils raised unreported exception
```

I am also pulling the container to my local machine to try it to see if the error is unique to the graham login node

**Comment by akhanf** [comment]
ok, digging a little more, it may be the container, @kaitj had run this successfully on graham login node, but the singularity hub container has been updated since then and now he is also seeing the same error.. @kaitj do you happen to still have the old container file?

**Comment by akhanf** [comment]
OK, @kaitj figured it out, you need the `-e` option when you run singularity exec, e.g.: 
singularity exec -e --nv deeplearning_gpu.simg net_download dense_vnet_abdominal_ct_model_zoo

The -e clears the environment, so perhaps something is messing up without it..

**Comment by nzxwang** [comment]
> OK, @kaitj figured it out, you need the `-e` option when you run singularity exec, e.g.:
> singularity exec -e --nv deeplearning_gpu.simg net_download dense_vnet_abdominal_ct_model_zoo
> 
> The -e clears the environment, so perhaps something is messing up without it..

Thanks, this solves it. Should I write a pull request for editting the readme or leave that up to you?

**Comment by akhanf** [comment]
> > OK, @kaitj figured it out, you need the `-e` option when you run singularity exec, e.g.:
> > singularity exec -e --nv deeplearning_gpu.simg net_download dense_vnet_abdominal_ct_model_zoo
> > The -e clears the environment, so perhaps something is messing up without it..
> 
> Thanks, this solves it. Should I write a pull request for editting the readme or leave that up to you?

That would be great, thanks!
